"""
Configuration Tab for Settings Window
Allows users to configure OpenAI and other settings via GUI
"""

import os
import json
from pathlib import Path
from PyQt5.QtCore import Qt
from PyQt5.QtWidgets import (
    QWidget, QVBoxLayout, QHBoxLayout, QFormLayout, QLabel, 
    QLineEdit, QPushButton, QComboBox, QFileDialog, QMessageBox
)
from PyQt5.QtGui import QFont

from milkchan.core.config import get_config, reload_config


class ConfigTab(QWidget):
    """Configuration tab for API and service settings"""
    
    def __init__(self, parent=None):
        super().__init__(parent)
        self.config = get_config()
        self.env_file = Path('.env')
        self.env_vars = self._load_env()
        self._build_ui()
        self._load_values()
    
    def _load_env(self) -> dict:
        """Load environment variables from .env file"""
        env = {}
        if self.env_file.exists():
            with open(self.env_file, 'r') as f:
                for line in f:
                    line = line.strip()
                    if line and not line.startswith('#') and '=' in line:
                        key, value = line.split('=', 1)
                        env[key.strip()] = value.strip()
        return env
    
    def _save_env(self, env: dict) -> bool:
        """Save environment variables to .env file"""
        try:
            with open(self.env_file, 'w') as f:
                f.write("# MilkChan Environment Configuration\n")
                f.write("# Generated by Settings Window\n\n")
                for key, value in env.items():
                    f.write(f"{key}={value}\n")
            return True
        except Exception as e:
            QMessageBox.critical(self, 'Error', f'Failed to save config: {e}')
            return False
    
    def _build_ui(self):
        """Build the UI"""
        layout = QVBoxLayout(self)
        layout.setContentsMargins(16, 16, 16, 16)
        layout.setSpacing(12)
        
        # Title
        title = QLabel('API & Service Configuration')
        title.setObjectName('title')
        title.setAlignment(Qt.AlignLeft | Qt.AlignVCenter)
        layout.addWidget(title)
        
        # Form
        form = QFormLayout()
        form.setLabelAlignment(Qt.AlignRight)
        form.setFormAlignment(Qt.AlignTop)
        form.setSpacing(10)
        
        # OpenAI API Key
        self.openai_key = QLineEdit()
        self.openai_key.setPlaceholderText('sk-...')
        self.openai_key.setEchoMode(QLineEdit.Password)
        form.addRow('OpenAI API Key:', self.openai_key)
        
        # OpenAI Base URL
        self.openai_base = QLineEdit()
        self.openai_base.setPlaceholderText('https://api.openai.com/v1')
        form.addRow('OpenAI Base URL:', self.openai_base)
        
        # Chat Model
        self.chat_model = QComboBox()
        self.chat_model.setEditable(True)
        self.chat_model.addItems([
            'gpt-4o-mini', 'gpt-4o', 'gpt-4-turbo', 
            'gpt-3.5-turbo', 'gpt-4'
        ])
        form.addRow('Chat Model:', self.chat_model)
        
        # Vision Model
        self.vision_model = QComboBox()
        self.vision_model.setEditable(True)
        self.vision_model.addItems([
            'gpt-4o-mini', 'gpt-4o', 'gpt-4-turbo',
            'gpt-4-vision-preview'
        ])
        form.addRow('Vision Model:', self.vision_model)
        
        layout.addLayout(form)
        
        # Buttons
        btn_layout = QHBoxLayout()
        btn_layout.addStretch()
        
        self.save_btn = QPushButton('Save & Restart')
        self.save_btn.setObjectName('saveButton')
        self.save_btn.clicked.connect(self._on_save)
        btn_layout.addWidget(self.save_btn)
        
        self.apply_btn = QPushButton('Apply')
        self.apply_btn.clicked.connect(self._on_apply)
        btn_layout.addWidget(self.apply_btn)
        
        self.reset_btn = QPushButton('Reset to Defaults')
        self.reset_btn.clicked.connect(self._on_reset)
        btn_layout.addWidget(self.reset_btn)
        
        layout.addLayout(btn_layout)
    
    def _load_values(self):
        """Load current values into UI"""
        self.openai_key.setText(self.env_vars.get('OPENAI_API_KEY', ''))
        self.openai_base.setText(self.env_vars.get('OPENAI_BASE_URL', 'https://api.openai.com/v1'))
        self.chat_model.setCurrentText(self.env_vars.get('OPENAI_CHAT_MODEL', 'gpt-4o-mini'))
        self.vision_model.setCurrentText(self.env_vars.get('OPENAI_VISION_MODEL', 'gpt-4o-mini'))

    def _on_save(self):
        """Save and prompt restart"""
        self._on_apply()
        QMessageBox.information(
            self, 'Saved',
            'Configuration saved. Restart the application for changes to take effect.'
        )

    def _on_apply(self):
        """Apply current values"""
        env = {
            'OPENAI_API_KEY': self.openai_key.text().strip(),
            'OPENAI_BASE_URL': self.openai_base.text().strip(),
            'OPENAI_CHAT_MODEL': self.chat_model.currentText().strip(),
            'OPENAI_VISION_MODEL': self.vision_model.currentText().strip(),
        }
        self._save_env(env)
        reload_config()

    def _on_reset(self):
        """Reset to defaults"""
        self.openai_key.setText('')
        self.openai_base.setText('https://api.openai.com/v1')
        self.chat_model.setCurrentText('gpt-4o-mini')
        self.vision_model.setCurrentText('gpt-4o-mini')